query GetExhibit($slug: String!) {
  exhibitCollection(limit: 1, where: { slug: $slug }) {
    items {
      sys {
        id
      }
      nameEn
      nameRu
      nameUz
      nameKa
      authorEn
      authorRu
      authorUz
      authorKa
      yearOfCreation
      descriptionEn {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          }
        }
      }
      descriptionRu {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          }
        }
      }
      descriptionUz {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          }
        }
      }
      descriptionKa {
        json
        links {
          entries {
            inline {
              sys {
                id
              }
            }
          }
        }
      }
      imagesCollection(limit: 5) {
        items {
          url
          sys {
            id
          }
        }
      }
      audioFileEn {
        url
      }
      audioFileRu {
        url
      }
      audioFileUz {
        url
      }
      audioFileKa {
        url
      }
    }
  }
}
