name: Continuous Deployment to Netlify

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [released]
env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_STAGING_SPACE_ID }}
  CONTENTFUL_CONTENT_DELIVERY_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_STAGING_CONTENT_DELIVERY_ACCESS_TOKEN }}
  CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_STAGING_CONTENT_PREVIEW_ACCESS_TOKEN }}
  CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
  CONTENTFUL_GTAG_ID: ${{ secrets.CONTENTFUL_STAGING_GTAG_ID }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test
      - name: Set environment variables for Staging and Dev
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'
        run: |
          echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_STAGING_SPACE_ID }}" >> $GITHUB_ENV
          echo "CONTENTFUL_CONTENT_DELIVERY_ACCESS_TOKEN=${{ secrets.CONTENTFUL_STAGING_CONTENT_DELIVERY_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN=${{ secrets.CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CONTENTFUL_ENVIRONMENT=${{ secrets.CONTENTFUL_ENVIRONMENT }}" >> $GITHUB_ENV
          echo "CONTENTFUL_GTAG_ID=${{ secrets.CONTENTFUL_STAGING_GTAG_ID }}" >> $GITHUB_ENV
      - name: Set environment variables for Release
        if: github.event_name == 'release' && github.event.action == 'released'
        run: |
          echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_STAGING_SPACE_ID }}" >> $GITHUB_ENV
          echo "CONTENTFUL_CONTENT_DELIVERY_ACCESS_TOKEN=${{ secrets.CONTENTFUL_STAGING_CONTENT_DELIVERY_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN=${{ secrets.CONTENTFUL_CONTENT_PREVIEW_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CONTENTFUL_ENVIRONMENT=${{ secrets.CONTENTFUL_ENVIRONMENT }}" >> $GITHUB_ENV
          echo "CONTENTFUL_GTAG_ID=${{ secrets.CONTENTFUL_STAGING_GTAG_ID }}" >> $GITHUB_ENV
      - name: Deploy Preview to Netlify
        if: github.event_name == 'pull_request'
        run: |
          netlify deploy \
            --build \
            --site ${{ secrets.NETLIFY_STAGING_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
      - name: Deploy Staging to Netlify
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          netlify deploy \
            --build \
            --prod \
            --site ${{ secrets.NETLIFY_STAGING_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
      - name: Deploy Production to Netlify
        if: github.event_name == 'release' && github.event.action == 'released'
        run: |
          netlify deploy \
            --build \
            --prod \
            --site ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}